# Generated by Django 4.2.7 on 2023-11-07 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_task_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 7, 56, 13, 299435, tzinfo=datetime.timezone.utc)),
        ),
    ]
